[theme]
base                     = "dark"
primaryColor             = "#00e5ff"
backgroundColor          = "#030b16"
secondaryBackgroundColor = "#060f1e"
textColor                = "#c8d8f0"
font                     = "sans serif"

[server]
headless             = true
enableCORS           = false
enableXsrfProtection = false
