name: xissin_app
description: Xissin Multi-Tool App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  device_info_plus: ^10.1.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  confetti: ^0.8.0
  url_launcher: ^6.3.0
  # ── Ads + IAP ──────────────────────────────────
  google_mobile_ads: ^5.1.0
  in_app_purchase: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
